### ISSUE TITLE
TS Case insensitive option?

### ISSUE THREAD

**Issue by ASoldo** [DariusCorvus/tree-sitter-surrealdb.nvim#4]
Hi, I've been using this plugin with AstroNvim (Lazy) and I've noticed that when i use lowercase letters (as it is supported by the SurrealDB) i can only get correct highlighting when in CAPS LOCK. Is it possible to be case insensitive?

example:
`from` and `FROM` will produce same color magenta.

Thank you and great work!

**Comment by dariuscorvus** [comment]
Hey, yes thats a good idea!
I will look into it. should be possible.

Thank you

**Comment by dariuscorvus** [comment]
Hey ASoldo,

I updated the surrealdb-treesitter parser living in this repository: https://github.com/DariusCorvus/tree-sitter-surrealdb

Now keywords are case insensitiv! 
Please run `:TSUpdate surrealdb`
That should pull the newest version from the parser repository.

Please leave me a notice when it is working and also when not :D

![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/61415118/a5e3fa56-c662-4ff5-895c-6d7757284655)

**Comment by ASoldo** [comment]
Awesome, Thank you! It seems to be working correctly now. I will test it more, if I find something: will let you know!

![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/1175537/eaf59933-e375-4978-91e5-6182be434a42)

**Comment by dariuscorvus** [comment]
I noticed that identifiers not correctly highlighted, like `name` which is yellow in your case and i think it should be white.

Like this
![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/61415118/dfeb5deb-d651-444f-8eb7-b8f07c5c0ce5)

what do you think?

**Comment by ASoldo** [comment]
I think yes, I think variables or properties could be white, just so its easy to get what is what.

**Comment by dariuscorvus** [comment]
Is fixed! feel free to update the plugin in your nvim config.
Thanks for your feedback.

**Comment by ASoldo** [comment]
This is how it looks now, name is still yellow after I've updated and restart Nvim.
I've done `:TsUpdate surrealdb` few times, is that ok?

![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/1175537/a00b9f8e-642c-44d9-88a6-506f519c2cf6)

**Comment by ASoldo** [comment]
also, you can see this situation, `when` is now wrong color, if I add any other character to it shows yellow otherwise is magenta. 
![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/1175537/e996bbc2-3b2d-43c5-8291-9d1d3486688a)
![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/1175537/749e978c-eb41-495a-83e8-80614c28f5a8)

This is my whole file with all demo queries I tried so far:
![image](https://github.com/DariusCorvus/tree-sitter-surrealdb.nvim/assets/1175537/7a9bcd2f-857d-4000-87cd-e942b27503cb)

**Comment by dariuscorvus** [comment]
could you tell me the colorscheme you are using?
then i will look into that with the same colors like yours, when i have time to do a deepdive :)

**Comment by ASoldo** [comment]
Sure, I'm using AstroNvim with defaults, no styling or any visual changes/plugins and the theme is called:
` colorscheme = "astrodark"`
